# Generated by Django 4.1.7 on 2023-04-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Bolim',
                'verbose_name_plural': 'Bolimlar',
            },
        ),
        migrations.CreateModel(
            name='Hodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_sharifi', models.CharField(max_length=200)),
                ('lavozimi', models.CharField(help_text='Lavozimingiz ', max_length=200)),
                ('stavka', models.FloatField()),
                ('bolimi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bolimlar')),
            ],
            options={
                'verbose_name': 'Hodim',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='Malumoti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tugilgan_yil', models.IntegerField()),
                ('millati', models.CharField(help_text='Millati: ', max_length=500)),
                ('tamomlagan', models.CharField(help_text='Bitirgan ', max_length=500)),
                ('mutaxasis', models.CharField(help_text='Soxasi ', max_length=500)),
                ('ilmiy_darajasi', models.CharField(help_text='Drajasi: ', max_length=500)),
                ('biladigan_tillari', models.CharField(help_text='tillar: ', max_length=500)),
                ('mukofotlari', models.CharField(help_text='muKofotlari ', max_length=500)),
                ('mehnat_faoliyati', models.TextField()),
                ('ism_sharifi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hodimlar')),
            ],
            options={
                'verbose_name': 'Malumot',
                'verbose_name_plural': 'Malumotlar',
            },
        ),
        migrations.CreateModel(
            name='Qarindoshlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qarindoshligi', models.CharField(help_text='Kim ekanini kiriting.....', max_length=500)),
                ('qarindosh_ismi', models.CharField(help_text='Qarindoshni kiriting.....', max_length=500)),
                ('qarindosh_tug_yil', models.DateField()),
                ('yashash_joyi', models.CharField(help_text='Yashash manzil...', max_length=500)),
                ('ish_joyi', models.CharField(help_text='Ish manzil...', max_length=500)),
                ('hodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.malumoti')),
            ],
            options={
                'verbose_name': 'Qarindoshi',
                'verbose_name_plural': 'Qarindoshlari',
            },
        ),
    ]
